# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from analyser import *
from doc_reader import DocReader
from doc_writer import DocWriter
from setting import *
import shutil

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 328)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.select_file = QtWidgets.QPushButton(self.tab)
        self.select_file.setObjectName("select_file")
        self.horizontalLayout_6.addWidget(self.select_file)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.convert = QtWidgets.QPushButton(self.tab)
        self.convert.setObjectName("convert")
        self.horizontalLayout_6.addWidget(self.convert)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.latex_flag = QtWidgets.QCheckBox(self.tab)
        self.latex_flag.setObjectName("latex_flag")
        self.horizontalLayout.addWidget(self.latex_flag)
        self.format_doc = QtWidgets.QCheckBox(self.tab)
        self.format_doc.setObjectName("format_doc")
        self.horizontalLayout.addWidget(self.format_doc)
        self.create_csv = QtWidgets.QCheckBox(self.tab)
        self.create_csv.setObjectName("create_csv")
        self.horizontalLayout.addWidget(self.create_csv)
        self.csv2excel = QtWidgets.QCheckBox(self.tab)
        self.csv2excel.setObjectName("csv2excel")
        self.horizontalLayout.addWidget(self.csv2excel)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_13.addWidget(self.label_21)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.file_name_label = QtWidgets.QLabel(self.tab)
        self.file_name_label.setText("")
        self.file_name_label.setObjectName("file_name_label")
        self.horizontalLayout_13.addWidget(self.file_name_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.score_label = QtWidgets.QLabel(self.tab)
        self.score_label.setText("")
        self.score_label.setObjectName("score_label")
        self.horizontalLayout_2.addWidget(self.score_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.out_of_label = QtWidgets.QLabel(self.tab)
        self.out_of_label.setText("")
        self.out_of_label.setObjectName("out_of_label")
        self.horizontalLayout_5.addWidget(self.out_of_label)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.pattern_matched_label = QtWidgets.QLabel(self.tab)
        self.pattern_matched_label.setText("")
        self.pattern_matched_label.setObjectName("pattern_matched_label")
        self.horizontalLayout_3.addWidget(self.pattern_matched_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.language_label = QtWidgets.QLabel(self.tab)
        self.language_label.setText("")
        self.language_label.setObjectName("language_label")
        self.horizontalLayout_4.addWidget(self.language_label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.progress_bar = QtWidgets.QProgressBar(self.tab)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_3.addWidget(self.progress_bar)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.status_box = QtWidgets.QTextBrowser(self.tab)
        self.status_box.setObjectName("status_box")
        self.verticalLayout_3.addWidget(self.status_box)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Added by me
        initialize()
        separate_dir()
        self.progress_bar.setValue(0)
        self.filename = ""
        self.path_ = ""
        self.data_blocks = []
        self.qoa = []
        self.list_dict = []
        self.score = 0
        self.select_file.clicked.connect(self.browse_file)
        self.convert.clicked.connect(self.writefiles)


    def browse_file(self):
        self.progress_bar.setValue(0)
        path = QFileDialog.getOpenFileName()[0]
        try:
            if len(path) > 0:
                self.path_= path
                fname = path.split("/")[-1]
                self.filename = fname
                self.get_data(not self.latex_flag.isChecked())
                self.set_file_properties()
            else:
                pass
        except:
            pass

    def get_data(self, latex_flag=False):
        error_code = -1
        reader = DocReader(self.path_)
        data = reader.read_file(latex_flag)
        if data != error_code:
            self.status_box.append("Data has been read successfully.")
            mapped_data = reader.map_data(data)
            if mapped_data != error_code:
                self.status_box.append("Data has been mapped successfully.")
                data_blocks = reader.make_blocks(mapped_data)
                if data_blocks != error_code:
                    self.status_box.append("Making block accomplished.")
                    self.data_blocks = data_blocks
                    qoa = reader.qoa_seperator(data_blocks)
                    if qoa != error_code:
                        self.status_box.append("Question, Option & Answer has been separated successfully.")
                        self.qoa = qoa
                        reader.remove_key(qoa, "sr.no.", "exam_tag")
                        list_dict = reader.make_dict(qoa)
                        if list_dict != error_code:
                            self.status_box.append("Making dictionaries accomplished.")
                            self.list_dict = list_dict
                        else:
                            self.status_box.append("Something went wrong while making dictionaries. Try again with latex code flag enabled.")
                    else:
                        self.status_box.append("Something went wrong while separating data.")
                else:
                    self.status_box.append("Something went wrong while making data blocks.")
            else:
                self.status_box.append("Something went wrong while mapping data")
        else:
            self.status_box.append("Something went wrong while reading Document.")


    def set_file_properties(self):
        try:
            analyser = Analyser(self.data_blocks)
            items_matched, items_count, score = analyser.check_pattern()
            language = analyser.get_language()
            self.score = score
            self.file_name_label.setText(self.filename)
            self.score_label.setText(str(round(items_matched, 2)))
            self.out_of_label.setText(str(items_count))
            self.pattern_matched_label.setText(str(round(score * 100, 2)))
            self.score = score
            self.language_label.setText(language)
            self.status_box.append("File has been successfully analysed.")
        except:
            self.status_box.append("Something went wrong while analysing the file.")

    def write2doc(self):
        os.chdir(docx_file_dir)
        new_doc_file = self.filename.replace(".docx", "-new.docx")
        writer = DocWriter(self.list_dict)
        progress = writer.write2doc(new_doc_file)
        for i in progress:
            self.progress_bar.setValue(i)
        self.status_box.append("docx file has been saved.")
        os.chdir("..")

    def write2csv(self):
        os.chdir(csv_file_dir)
        new_csv_file = self.filename.replace(".docx", "-new.csv")
        writer = DocWriter(self.list_dict)
        writer.to_csv(new_csv_file)
        for i in range(100):
            self.progress_bar.setValue(i+1)
        self.status_box.append("csv file has been saved.")
        os.chdir("..")

    def write2excel(self):
        os.chdir(excel_file_dir)
        new_csv_file = self.filename.replace(".docx", "-new.csv")
        new_excel_file = self.filename.replace(".docx", "-new.xlsx")
        writer = DocWriter(self.list_dict)
        writer.to_csv(new_csv_file)
        writer.csv2excel(new_csv_file,new_excel_file )
        os.remove(new_csv_file)
        for i in range(100):
            self.progress_bar.setValue(i+1)
        self.status_box.append("excel file has been saved.")
        os.chdir("..")

    def writefiles(self):
        funcList = [self.write2doc, self.write2csv, self.write2excel]
        bol = [self.format_doc.isChecked(), self.create_csv.isChecked(), self.csv2excel.isChecked()]
        if self.score > 0.85:
            run_mul(funcList, bol)
        else:
            self.status_box.append("Score is below threshold value.")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Disha Test Board"))
        self.select_file.setText(_translate("MainWindow", "Select File"))
        self.convert.setText(_translate("MainWindow", "Convert"))
        self.latex_flag.setText(_translate("MainWindow", "Don't read Latex"))
        self.format_doc.setText(_translate("MainWindow", "Format Doc"))
        self.create_csv.setText(_translate("MainWindow", "Create CSV"))
        self.csv2excel.setText(_translate("MainWindow", "CSV to Excel"))
        self.label_9.setText(_translate("MainWindow", "Properties"))
        self.label_21.setText(_translate("MainWindow", "File Name"))
        self.label.setText(_translate("MainWindow", "Score"))
        self.label_7.setText(_translate("MainWindow", "Out Of"))
        self.label_3.setText(_translate("MainWindow", "Pattern Matched"))
        self.label_5.setText(_translate("MainWindow", "Language"))
        self.label_10.setText(_translate("MainWindow", "Status Box"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "DocFormatter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.setMinimumWidth(1080)
    MainWindow.setMinimumHeight(480)
    MainWindow.show()
    sys.exit(app.exec_())
